using System.ComponentModel;
using System.Collections.ObjectModel;

namespace syncfusion.dropdowndemos.wpf
{
    public class FoodModel
    {
        public FoodModel()
        {
        }
        public string Name { get; set; }
    }

    public class FoodViewModel : INotifyPropertyChanged
    {
        private ObservableCollection<FoodModel> foods;

        public ObservableCollection<FoodModel> Foods
        {
            get { return foods; }
            set { foods = value; OnPropertyChanged(nameof(Foods)); }
        }
        public FoodViewModel()
        {
            foods = new ObservableCollection<FoodModel>
             {
                new FoodModel { Name = "Acai Bowl" },
                new FoodModel { Name = "Aloo Gobi" },
                new FoodModel { Name = "Arepas" },
                new FoodModel { Name = "Baba Ganoush" },
                new FoodModel { Name = "Bagels" },
                new FoodModel { Name = "Bahn Xeo" },
                new FoodModel { Name = "Baklava" },
                new FoodModel { Name = "Banana Bread" },
                new FoodModel { Name = "Barbecue Ribs" },
                new FoodModel { Name = "Beef Bourguignon" },
                new FoodModel { Name = "Beef Wellington" },
                new FoodModel { Name = "Beignets" },
                new FoodModel { Name = "Biryani" },
                new FoodModel { Name = "Black Pudding" },
                new FoodModel { Name = "Blini" },
                new FoodModel { Name = "Bobotie" },
                new FoodModel { Name = "Bratwurst" },
                new FoodModel { Name = "Bruschetta" },
                new FoodModel { Name = "Bubble Tea" },
                new FoodModel { Name = "Buffalo Wings" },
                new FoodModel { Name = "Bulgogi" },
                new FoodModel { Name = "Burek" },
                new FoodModel { Name = "Butter Chicken" },
                new FoodModel { Name = "Cacio e Pepe" },
                new FoodModel { Name = "Caesar Salad" },
                new FoodModel { Name = "Calamari" },
                new FoodModel { Name = "Ceviche" },
                new FoodModel { Name = "Chana Masala" },
                new FoodModel { Name = "Cheeseburger" },
                new FoodModel { Name = "Chicken Adobo" },
                new FoodModel { Name = "Chicken Kiev" },
                new FoodModel { Name = "Chicken Parmigiana" },
                new FoodModel { Name = "Chicken Tikka Masala" },
                new FoodModel { Name = "Chili Con Carne" },
                new FoodModel { Name = "Chimichanga" },
                new FoodModel { Name = "Chips and Salsa" },
                new FoodModel { Name = "Churros" },
                new FoodModel { Name = "Clam Chowder" },
                new FoodModel { Name = "Cochinita Pibil" },
                new FoodModel { Name = "Cornbread" },
                new FoodModel { Name = "Croissants" },
                new FoodModel { Name = "Cuban Sandwich" },
                new FoodModel { Name = "Currywurst" },
                new FoodModel { Name = "Dim Sum" },
                new FoodModel { Name = "Donburi" },
                new FoodModel { Name = "Donuts" },
                new FoodModel { Name = "Dosas" },
                new FoodModel { Name = "Dumplings" },
                new FoodModel { Name = "Eclairs" },
                new FoodModel { Name = "Eggs Benedict" },
                new FoodModel { Name = "Empanadas" },
                new FoodModel { Name = "Enchiladas" },
                new FoodModel { Name = "Falafel" },
                new FoodModel { Name = "Fettuccine Alfredo" },
                new FoodModel { Name = "Fish and Chips" },
                new FoodModel { Name = "Focaccia" },
                new FoodModel { Name = "Fondue" },
                new FoodModel { Name = "French Fries" },
                new FoodModel { Name = "French Onion Soup" },
                new FoodModel { Name = "Fried Calamari" },
                new FoodModel { Name = "Fried Rice" },
                new FoodModel { Name = "Frittata" },
                new FoodModel { Name = "Frog Legs" },
                new FoodModel { Name = "Gado-Gado" },
                new FoodModel { Name = "Galbi" },
                new FoodModel { Name = "Galette" },
                new FoodModel { Name = "Garlic Bread" },
                new FoodModel { Name = "Gazpacho" },
                new FoodModel { Name = "Gelato" },
                new FoodModel { Name = "Gimbap" },
                new FoodModel { Name = "Gnocchi" },
                new FoodModel { Name = "Greek Salad" },
                new FoodModel { Name = "Grits" },
                new FoodModel { Name = "Gulab Jamun" },
                new FoodModel { Name = "Gumbo" },
                new FoodModel { Name = "Gyros" },
                new FoodModel { Name = "Haggis" },
                new FoodModel { Name = "Halo-Halo" },
                new FoodModel { Name = "Hamburger" },
                new FoodModel { Name = "Hummus" },
                new FoodModel { Name = "Ice Cream" },
                new FoodModel { Name = "Idli" },
                new FoodModel { Name = "Irish Stew" },
                new FoodModel { Name = "Jambalaya" },
                new FoodModel { Name = "Japanese Curry" },
                new FoodModel { Name = "Jollof Rice" },
                new FoodModel { Name = "Kadhi" },
                new FoodModel { Name = "Kare-Kare" },
                new FoodModel { Name = "Katsudon" },
                new FoodModel { Name = "Kimchi" },
                new FoodModel { Name = "Kofta" },
                new FoodModel { Name = "Koshari" },
                new FoodModel { Name = "Kouign-Amann" },
                new FoodModel { Name = "Kreplach" },
                new FoodModel { Name = "Krispy Kreme Doughnuts" },
                new FoodModel { Name = "Kumpir" },
                new FoodModel { Name = "Kung Pao Chicken" },
                new FoodModel { Name = "Lamb Kebab" },
                new FoodModel { Name = "Larb" },
                new FoodModel { Name = "Lasagna" },
                new FoodModel { Name = "Lassi" },
                new FoodModel { Name = "Lechon" },
                new FoodModel { Name = "Lobster Bisque" },
                new FoodModel { Name = "Lobster Roll" },
                new FoodModel { Name = "Lokum" },
                new FoodModel { Name = "Mac and Cheese" },
                new FoodModel { Name = "Maki Rolls" },
                new FoodModel { Name = "Malai Kofta" },
                new FoodModel { Name = "Manti" },
                new FoodModel { Name = "Maple Syrup Pancakes" },
                new FoodModel { Name = "Margarita Pizza" },
                new FoodModel { Name = "Masala Chai" },
                new FoodModel { Name = "Matar Paneer" },
                new FoodModel { Name = "Maultaschen" },
                new FoodModel { Name = "Miso Soup" },
                new FoodModel { Name = "Mochi" },
                new FoodModel { Name = "Moussaka" },
                new FoodModel { Name = "Muffuletta" },
                new FoodModel { Name = "Naan" },
                new FoodModel { Name = "Nachos" },
                new FoodModel { Name = "Nasi Goreng" },
                new FoodModel { Name = "New England Clam Chowder" },
                new FoodModel { Name = "Okonomiyaki" },
                new FoodModel { Name = "Onigiri" },
                new FoodModel { Name = "Osso Buco" },
                new FoodModel { Name = "Otak-Otak" },
                new FoodModel { Name = "Pad Thai" },
                new FoodModel { Name = "Pakora" },
                new FoodModel { Name = "Palak Paneer" },
                new FoodModel { Name = "Paneer Tikka" },
                new FoodModel { Name = "Panna Cotta" },
                new FoodModel { Name = "Peking Duck" },
                new FoodModel { Name = "Pho" },
                new FoodModel { Name = "Pierogi" },
                new FoodModel { Name = "Piri Piri Chicken" },
                new FoodModel { Name = "Pizza Margherita" },
                new FoodModel { Name = "Plov" },
                new FoodModel { Name = "Po' Boy Sandwich" },
                new FoodModel { Name = "Poffertjes" },
                new FoodModel { Name = "Polenta" },
                new FoodModel { Name = "Popcorn" },
                new FoodModel { Name = "Pork Belly" },
                new FoodModel { Name = "Poutine" },
                new FoodModel { Name = "Pretzels" },
                new FoodModel { Name = "Quesadillas" },
                new FoodModel { Name = "Raclette" },
                new FoodModel { Name = "Ramen" },
                new FoodModel { Name = "Ratatouille" },
                new FoodModel { Name = "Ravioli" },
                new FoodModel { Name = "Red Velvet Cake" },
                new FoodModel { Name = "Rendang" },
                new FoodModel { Name = "Rice and Beans" },
                new FoodModel { Name = "Rogan Josh" },
                new FoodModel { Name = "Rosti" },
                new FoodModel { Name = "Roti" },
                new FoodModel { Name = "Sachertorte" },
                new FoodModel { Name = "Samosas" },
                new FoodModel { Name = "Sauerbraten" },
                new FoodModel { Name = "Schnitzel" },
                new FoodModel { Name = "Shakshuka" },
                new FoodModel { Name = "Shawarma" },
                new FoodModel { Name = "Shepherd's Pie" },
                new FoodModel { Name = "Shu Mai" },
                new FoodModel { Name = "Singapore Noodles" },
                new FoodModel { Name = "Som Tum" },
                new FoodModel { Name = "Sopes" },
                new FoodModel { Name = "Spanakopita" },
                new FoodModel { Name = "Spaghetti Bolognese" },
                new FoodModel { Name = "Spaghetti Carbonara" },
                new FoodModel { Name = "Spring Rolls" },
                new FoodModel { Name = "Steak Frites" },
                new FoodModel { Name = "Sticky Toffee Pudding" },
                new FoodModel { Name = "Stuffed Grape Leaves" },
                new FoodModel { Name = "Sukiyaki" },
                new FoodModel { Name = "Sushi" },
                new FoodModel { Name = "Sweet and Sour Pork" },
                new FoodModel { Name = "Tabbouleh" },
                new FoodModel { Name = "Takoyaki" },
                new FoodModel { Name = "Tamales" },
                new FoodModel { Name = "Tandoori Chicken" },
                new FoodModel { Name = "Tapenade" },
                new FoodModel { Name = "Tempura" },
                new FoodModel { Name = "Tiramisu" },
                new FoodModel { Name = "Tonkatsu" },
                new FoodModel { Name = "Tortilla Española" },
                new FoodModel { Name = "Tostones" },
                new FoodModel { Name = "Tzatziki" },
                new FoodModel { Name = "Udon" },
                new FoodModel { Name = "Vada Pav" },
                new FoodModel { Name = "Vindaloo" },
                new FoodModel { Name = "Waffles" },
                new FoodModel { Name = "Wasabi Peas" },
                new FoodModel { Name = "Xiao Long Bao" },
                new FoodModel { Name = "Yakitori" },
                new FoodModel { Name = "Yakisoba" },
                new FoodModel { Name = "Yogurt" },
                new FoodModel { Name = "Zaatar Manakish" },
                new FoodModel { Name = "Zeppole" },
                new FoodModel { Name = "Zongzi" }
            };
        }

        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}