#pragma checksum "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CDD0B79046C8F77533F3875BD42C8E397FBB96CC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.PivotAnalysis.Base;
using Syncfusion.Windows;
using Syncfusion.Windows.Collections;
using Syncfusion.Windows.ComponentModel;
using Syncfusion.Windows.Controls.Cells;
using Syncfusion.Windows.Controls.Grid;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.PivotGrid;
using Syncfusion.Windows.Controls.PivotSchemaDesigner;
using Syncfusion.Windows.Controls.Scroll;
using Syncfusion.Windows.Controls.VirtualTreeView;
using Syncfusion.Windows.Data;
using Syncfusion.Windows.Diagnostics;
using Syncfusion.Windows.GridCommon;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Styles;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.pivotgriddemos.wpf;


namespace syncfusion.pivotgriddemos.wpf {
    
    
    /// <summary>
    /// PivotUpdating
    /// </summary>
    public partial class PivotUpdating : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.PivotGrid.PivotGridControl pivotGrid1;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.PivotSchemaDesigner.PivotSchemaDesigner SchemaDesigner;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkEnableUpdate;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkTimerUpdate;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbUpdateRate;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddTop;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddMid;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddBot;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.pivotgriddemos.wpf;component/views/interactive%20features/pivotupdati" +
                    "ng.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Interactive Features\PivotUpdating.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pivotGrid1 = ((Syncfusion.Windows.Controls.PivotGrid.PivotGridControl)(target));
            return;
            case 2:
            this.SchemaDesigner = ((Syncfusion.Windows.Controls.PivotSchemaDesigner.PivotSchemaDesigner)(target));
            return;
            case 3:
            this.chkEnableUpdate = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 4:
            this.chkTimerUpdate = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.cmbUpdateRate = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.btnAddTop = ((System.Windows.Controls.Button)(target));
            return;
            case 7:
            this.btnAddMid = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.btnAddBot = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

