#pragma checksum "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FB1FF8CF61256DD1FE0894484000B6A27B858DB8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.Windows;
using Syncfusion.Windows.Collections;
using Syncfusion.Windows.ComponentModel;
using Syncfusion.Windows.Controls.Cells;
using Syncfusion.Windows.Controls.Grid;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Media;
using Syncfusion.Windows.Controls.Navigation;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.Scroll;
using Syncfusion.Windows.Controls.VirtualTreeView;
using Syncfusion.Windows.Data;
using Syncfusion.Windows.Diagnostics;
using Syncfusion.Windows.GridCommon;
using Syncfusion.Windows.PropertyGrid;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Styles;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using Syncfusion.Windows.Tools.MVVM;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.editordemos.wpf;


namespace syncfusion.editordemos.wpf {
    
    
    /// <summary>
    /// ColorPickerPaletteDemo
    /// </summary>
    public partial class ColorPickerPaletteDemo : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 31 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ThemePanel;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox StandardColorPanel;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox RecentColorPanel;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox MoreColorOption;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox StandardTab;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CustomTab;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.ComboBoxAdv cmbothemecolors;
        
        #line default
        #line hidden
        
        
        #line 149 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.ColorPickerPalette ColorPickerPalette1;
        
        #line default
        #line hidden
        
        
        #line 180 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.ColorPickerPalette ColorPickerPalette2;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.editordemos.wpf;component/colorpickerpalette/colorpickerpalettedemo.x" +
                    "aml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\ColorPickerPalette\ColorPickerPaletteDemo.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ThemePanel = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 2:
            this.StandardColorPanel = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.RecentColorPanel = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 4:
            this.MoreColorOption = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.StandardTab = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.CustomTab = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.cmbothemecolors = ((Syncfusion.Windows.Tools.Controls.ComboBoxAdv)(target));
            return;
            case 8:
            this.ColorPickerPalette1 = ((Syncfusion.Windows.Tools.Controls.ColorPickerPalette)(target));
            return;
            case 9:
            this.ColorPickerPalette2 = ((Syncfusion.Windows.Tools.Controls.ColorPickerPalette)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

