#pragma checksum "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8772FCDF93DC44DD26C2525E5E040EFE90D6E0F4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xaml.Behaviors;
using Microsoft.Xaml.Behaviors.Core;
using Microsoft.Xaml.Behaviors.Input;
using Microsoft.Xaml.Behaviors.Layout;
using Microsoft.Xaml.Behaviors.Media;
using Syncfusion;
using Syncfusion.PivotAnalysis.Base;
using Syncfusion.Windows;
using Syncfusion.Windows.Collections;
using Syncfusion.Windows.ComponentModel;
using Syncfusion.Windows.Controls.Cells;
using Syncfusion.Windows.Controls.Grid;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.PivotGrid;
using Syncfusion.Windows.Controls.PivotSchemaDesigner;
using Syncfusion.Windows.Controls.Scroll;
using Syncfusion.Windows.Controls.VirtualTreeView;
using Syncfusion.Windows.Data;
using Syncfusion.Windows.Diagnostics;
using Syncfusion.Windows.GridCommon;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Styles;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.pivotgriddemos.wpf;


namespace syncfusion.pivotgriddemos.wpf {
    
    
    /// <summary>
    /// HyperlinkCell
    /// </summary>
    public partial class HyperlinkCell : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.PivotGrid.PivotGridControl pivotGrid1;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox LstBoxHyperlinkCellClickEventArgs;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.PivotSchemaDesigner.PivotSchemaDesigner SchemaDesigner;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ColumnHeaderCellBox;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox RowHeaderCellBox;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SummaryHeaderSBox;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SummaryCellBox;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ValueCellBox;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Clear;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.pivotgriddemos.wpf;component/views/appearance/hyperlinkcell.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Appearance\HyperlinkCell.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pivotGrid1 = ((Syncfusion.Windows.Controls.PivotGrid.PivotGridControl)(target));
            return;
            case 2:
            this.LstBoxHyperlinkCellClickEventArgs = ((System.Windows.Controls.ListBox)(target));
            return;
            case 3:
            this.SchemaDesigner = ((Syncfusion.Windows.Controls.PivotSchemaDesigner.PivotSchemaDesigner)(target));
            return;
            case 4:
            this.ColumnHeaderCellBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.RowHeaderCellBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.SummaryHeaderSBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.SummaryCellBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.ValueCellBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 9:
            this.Clear = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

