#pragma checksum "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "71C86D0E361B0652A17799378F79F306FB3B43191BAB9EA9896BDA0037E4ACF9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.Windows;
using Syncfusion.Windows.Collections;
using Syncfusion.Windows.ComponentModel;
using Syncfusion.Windows.Controls.Cells;
using Syncfusion.Windows.Controls.Grid;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Media;
using Syncfusion.Windows.Controls.Navigation;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.Scroll;
using Syncfusion.Windows.Controls.VirtualTreeView;
using Syncfusion.Windows.Data;
using Syncfusion.Windows.Diagnostics;
using Syncfusion.Windows.GridCommon;
using Syncfusion.Windows.PropertyGrid;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Styles;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using Syncfusion.Windows.Tools.MVVM;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.editordemos.wpf;


namespace syncfusion.editordemos.wpf {
    
    
    /// <summary>
    /// TimeSpanEditDemo
    /// </summary>
    public partial class TimeSpanEditDemo : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 59 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Shared.TimeSpanEdit mintimespanedit;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Shared.TimeSpanEdit maxtimespanedit;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox txtformat;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkarrowvisibility;
        
        #line default
        #line hidden
        
        
        #line 147 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkscrolling;
        
        #line default
        #line hidden
        
        
        #line 171 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkallownull;
        
        #line default
        #line hidden
        
        
        #line 186 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtnullstring;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSetNull;
        
        #line default
        #line hidden
        
        
        #line 210 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Shared.TimeSpanEdit myTimeSpanEdit;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.editordemos.wpf;component/timespanedit/timespaneditdemo.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\TimeSpanEdit\TimeSpanEditDemo.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.mintimespanedit = ((Syncfusion.Windows.Shared.TimeSpanEdit)(target));
            return;
            case 2:
            this.maxtimespanedit = ((Syncfusion.Windows.Shared.TimeSpanEdit)(target));
            return;
            case 3:
            this.txtformat = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.chkarrowvisibility = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.chkscrolling = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.chkallownull = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.txtnullstring = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.btnSetNull = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.myTimeSpanEdit = ((Syncfusion.Windows.Shared.TimeSpanEdit)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

