#pragma checksum "..\..\..\..\Views\CreateLettersDemo.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A748D697F7942757AA4C7FEC37A882841D4C667F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.Primitives;
using Syncfusion.Windows.Controls.RichTextBoxAdv;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.documenteditor.wpf;
using syncfusion.richtextboxdemos.wpf;


namespace syncfusion.richtextboxdemos.wpf {
    
    
    /// <summary>
    /// CreateLettersDemo
    /// </summary>
    public partial class CreateLettersDemo : Syncfusion.Windows.Tools.Controls.RibbonWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.richtextboxdemos.wpf.CreateLettersDemo ribbonWindow;
        
        #line default
        #line hidden
        
        
        #line 3875 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.documenteditor.wpf.RunAdv currentPageNumberRun;
        
        #line default
        #line hidden
        
        
        #line 3877 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.documenteditor.wpf.RunAdv pagecountRun;
        
        #line default
        #line hidden
        
        
        #line 3909 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfRangeSlider rangeslider;
        
        #line default
        #line hidden
        
        
        #line 3916 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Root;
        
        #line default
        #line hidden
        
        
        #line 3922 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.RichTextBoxAdv.SfRichTextRibbon richTextRibbon;
        
        #line default
        #line hidden
        
        
        #line 3923 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.RichTextBoxAdv.SfRichTextBoxAdv richTextBoxAdv;
        
        #line default
        #line hidden
        
        
        #line 4185 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.RichTextBoxAdv.UIContainerAdv dateTimeEdit;
        
        #line default
        #line hidden
        
        
        #line 4344 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ContactName;
        
        #line default
        #line hidden
        
        
        #line 4364 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CompanyName;
        
        #line default
        #line hidden
        
        
        #line 4384 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Address;
        
        #line default
        #line hidden
        
        
        #line 4404 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox City;
        
        #line default
        #line hidden
        
        
        #line 4419 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Country;
        
        #line default
        #line hidden
        
        
        #line 4456 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Phone;
        
        #line default
        #line hidden
        
        
        #line 4480 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Fax;
        
        #line default
        #line hidden
        
        
        #line 4524 "..\..\..\..\Views\CreateLettersDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ContactName2;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.richtextboxdemos.wpf;component/views/createlettersdemo.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\CreateLettersDemo.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ribbonWindow = ((syncfusion.richtextboxdemos.wpf.CreateLettersDemo)(target));
            return;
            case 2:
            this.currentPageNumberRun = ((syncfusion.documenteditor.wpf.RunAdv)(target));
            return;
            case 3:
            this.pagecountRun = ((syncfusion.documenteditor.wpf.RunAdv)(target));
            return;
            case 4:
            this.rangeslider = ((Syncfusion.Windows.Controls.Input.SfRangeSlider)(target));
            return;
            case 5:
            this.Root = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.richTextRibbon = ((Syncfusion.Windows.Controls.RichTextBoxAdv.SfRichTextRibbon)(target));
            return;
            case 7:
            this.richTextBoxAdv = ((Syncfusion.Windows.Controls.RichTextBoxAdv.SfRichTextBoxAdv)(target));
            return;
            case 8:
            this.dateTimeEdit = ((Syncfusion.Windows.Controls.RichTextBoxAdv.UIContainerAdv)(target));
            return;
            case 9:
            this.ContactName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.CompanyName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.Address = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.City = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.Country = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.Phone = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.Fax = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.ContactName2 = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

