#pragma checksum "..\..\..\..\Views\RightToLeftDemo.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A304879933BF5ECF7D588740F4C3E16AF2DA28EF"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.RichTextBoxAdv;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.documenteditor.wpf;


namespace syncfusion.richtextboxdemos.wpf {
    
    
    /// <summary>
    /// RightToLeftDemo
    /// </summary>
    public partial class RightToLeftDemo : Syncfusion.Windows.Tools.Controls.RibbonWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\Views\RightToLeftDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.richtextboxdemos.wpf.RightToLeftDemo ribbonWindow;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\Views\RightToLeftDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.documenteditor.wpf.RunAdv currentPageNumberRun;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\Views\RightToLeftDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.documenteditor.wpf.RunAdv pagecountRun;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\Views\RightToLeftDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfRangeSlider rangeslider;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\..\Views\RightToLeftDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Root;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\Views\RightToLeftDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.RichTextBoxAdv.SfRichTextRibbon richTextRibbon;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\Views\RightToLeftDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.RichTextBoxAdv.SfRichTextBoxAdv richTextBoxAdv;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.richtextboxdemos.wpf;component/views/righttoleftdemo.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\RightToLeftDemo.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ribbonWindow = ((syncfusion.richtextboxdemos.wpf.RightToLeftDemo)(target));
            return;
            case 2:
            this.currentPageNumberRun = ((syncfusion.documenteditor.wpf.RunAdv)(target));
            return;
            case 3:
            this.pagecountRun = ((syncfusion.documenteditor.wpf.RunAdv)(target));
            return;
            case 4:
            this.rangeslider = ((Syncfusion.Windows.Controls.Input.SfRangeSlider)(target));
            return;
            case 5:
            this.Root = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.richTextRibbon = ((Syncfusion.Windows.Controls.RichTextBoxAdv.SfRichTextRibbon)(target));
            return;
            case 7:
            this.richTextBoxAdv = ((Syncfusion.Windows.Controls.RichTextBoxAdv.SfRichTextBoxAdv)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

