#pragma checksum "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FE2B654C39F705A32CE5E4FF600F7FD2F36EFBEE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xaml.Behaviors;
using Microsoft.Xaml.Behaviors.Core;
using Microsoft.Xaml.Behaviors.Input;
using Microsoft.Xaml.Behaviors.Layout;
using Microsoft.Xaml.Behaviors.Media;
using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.UI.Xaml.Controls.DataPager;
using Syncfusion.UI.Xaml.Grid;
using Syncfusion.UI.Xaml.Grid.RowFilter;
using Syncfusion.UI.Xaml.TreeGrid;
using Syncfusion.UI.Xaml.TreeGrid.Filtering;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.dropdowndemos.wpf;


namespace syncfusion.dropdowndemos.wpf {
    
    
    /// <summary>
    /// MultiColumnDropDownDemo
    /// </summary>
    public partial class MultiColumnDropDownDemo : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 49 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label1;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl MultiColumnControl;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label2;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl MultiColumnControl1;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label3;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl MultiColumnControl2;
        
        #line default
        #line hidden
        
        
        #line 152 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label4;
        
        #line default
        #line hidden
        
        
        #line 159 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl MultiColumnControl3;
        
        #line default
        #line hidden
        
        
        #line 186 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label5;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl MultiColumnControl4;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label6;
        
        #line default
        #line hidden
        
        
        #line 228 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl MultiColumnControl5;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.dropdowndemos.wpf;component/multi%20column%20dropdown/multicolumndrop" +
                    "downdemo.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Multi Column Dropdown\MultiColumnDropDownDemo.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.label1 = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.MultiColumnControl = ((Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl)(target));
            return;
            case 3:
            this.label2 = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.MultiColumnControl1 = ((Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl)(target));
            return;
            case 5:
            this.label3 = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.MultiColumnControl2 = ((Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl)(target));
            return;
            case 7:
            this.label4 = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.MultiColumnControl3 = ((Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl)(target));
            return;
            case 9:
            this.label5 = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.MultiColumnControl4 = ((Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl)(target));
            return;
            case 11:
            this.label6 = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.MultiColumnControl5 = ((Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

