#pragma checksum "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "70ECBE7009531711B37C5362AF676B24DD3DB5A4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.PivotAnalysis.Base;
using Syncfusion.Windows;
using Syncfusion.Windows.Collections;
using Syncfusion.Windows.ComponentModel;
using Syncfusion.Windows.Controls.Cells;
using Syncfusion.Windows.Controls.Grid;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.PivotGrid;
using Syncfusion.Windows.Controls.PivotSchemaDesigner;
using Syncfusion.Windows.Controls.Scroll;
using Syncfusion.Windows.Controls.VirtualTreeView;
using Syncfusion.Windows.Data;
using Syncfusion.Windows.Diagnostics;
using Syncfusion.Windows.GridCommon;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Styles;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.pivotgriddemos.wpf;


namespace syncfusion.pivotgriddemos.wpf {
    
    
    /// <summary>
    /// ContextMenu
    /// </summary>
    public partial class ContextMenu : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.PivotGrid.PivotGridControl pivotGrid1;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.PivotSchemaDesigner.PivotSchemaDesigner SchemaDesigner;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpdateItemsSource;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkEnableContextMenuRow;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkEnableContextMenuCol;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCollapseRow;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCollapseCol;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCollapseRowList;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCollapseColList;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnExpandRow;
        
        #line default
        #line hidden
        
        
        #line 177 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnExpandCol;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnExpandRowList;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnExpandColList;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.pivotgriddemos.wpf;component/views/grouping%20bar/contextmenu.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Grouping Bar\ContextMenu.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pivotGrid1 = ((Syncfusion.Windows.Controls.PivotGrid.PivotGridControl)(target));
            return;
            case 2:
            this.SchemaDesigner = ((Syncfusion.Windows.Controls.PivotSchemaDesigner.PivotSchemaDesigner)(target));
            return;
            case 3:
            this.btnUpdateItemsSource = ((System.Windows.Controls.Button)(target));
            return;
            case 4:
            this.chkEnableContextMenuRow = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.chkEnableContextMenuCol = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.btnCollapseRow = ((System.Windows.Controls.Button)(target));
            return;
            case 7:
            this.btnCollapseCol = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.btnCollapseRowList = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.btnCollapseColList = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.btnExpandRow = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.btnExpandCol = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.btnExpandRowList = ((System.Windows.Controls.Button)(target));
            return;
            case 13:
            this.btnExpandColList = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

