#pragma checksum "..\..\..\..\DatePicker\DatePickerDemo.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "821266F1C2DBECEA4252DDFC07EE6FD6830D8DC9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.Windows;
using Syncfusion.Windows.Collections;
using Syncfusion.Windows.ComponentModel;
using Syncfusion.Windows.Controls.Cells;
using Syncfusion.Windows.Controls.Grid;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Media;
using Syncfusion.Windows.Controls.Navigation;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.Scroll;
using Syncfusion.Windows.Controls.VirtualTreeView;
using Syncfusion.Windows.Data;
using Syncfusion.Windows.Diagnostics;
using Syncfusion.Windows.GridCommon;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Styles;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.editordemos.wpf;


namespace syncfusion.editordemos.wpf {
    
    
    /// <summary>
    /// DatePickerDemo
    /// </summary>
    public partial class DatePickerDemo : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 121 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker DefaultDatePicker;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker EditDatePicker;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker CustomDatePicker;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker NullableDatePicker;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker FormatDatePicker;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker ReadableDatePicker;
        
        #line default
        #line hidden
        
        
        #line 243 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker MinMaxDatePicker;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker CustomTemplateDatePicker;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfDatePicker CustomDropDownHeightDatePicker;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.editordemos.wpf;component/datepicker/datepickerdemo.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\DatePicker\DatePickerDemo.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DefaultDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            case 2:
            this.EditDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            case 3:
            this.CustomDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            case 4:
            this.NullableDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            case 5:
            this.FormatDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            case 6:
            this.ReadableDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            case 7:
            this.MinMaxDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            case 8:
            this.CustomTemplateDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            case 9:
            this.CustomDropDownHeightDatePicker = ((Syncfusion.Windows.Controls.Input.SfDatePicker)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

