#region Copyright Syncfusion Inc. 2001-2022.
// Copyright Syncfusion Inc. 2001-2022. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
#pragma checksum "..\..\..\..\Views\NetworkDiagram.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "AF383D3DDB841C63C306EFFC1573DCF569992CC6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.UI.Xaml.Diagram;
using Syncfusion.UI.Xaml.Diagram.Controls;
using Syncfusion.UI.Xaml.Diagram.Layout;
using Syncfusion.UI.Xaml.Diagram.Panels;
using Syncfusion.UI.Xaml.Diagram.Stencil;
using Syncfusion.UI.Xaml.Diagram.Theming;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.networkdiagram.wpf.ViewModel;
using syncfusion.networkdiagram.wpf.Views;


namespace syncfusion.networkdiagram.wpf.Views {
    
    
    /// <summary>
    /// NetworkDiagramDemo
    /// </summary>
    public partial class NetworkDiagramDemo : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 1340 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem SelectionTool;
        
        #line default
        #line hidden
        
        
        #line 1341 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem PanTool;
        
        #line default
        #line hidden
        
        
        #line 1342 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem DrawTool;
        
        #line default
        #line hidden
        
        
        #line 1351 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ShowLines;
        
        #line default
        #line hidden
        
        
        #line 1352 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem SnapToGrid;
        
        #line default
        #line hidden
        
        
        #line 1353 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem SnapToObject;
        
        #line default
        #line hidden
        
        
        #line 1354 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ShowRuler;
        
        #line default
        #line hidden
        
        
        #line 1355 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ShowPageBreaks;
        
        #line default
        #line hidden
        
        
        #line 1357 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem FitToWidth;
        
        #line default
        #line hidden
        
        
        #line 1358 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem FitToPage;
        
        #line default
        #line hidden
        
        
        #line 1359 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ResetView;
        
        #line default
        #line hidden
        
        
        #line 1369 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button NewButton;
        
        #line default
        #line hidden
        
        
        #line 1380 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LoadFromTemplateButton;
        
        #line default
        #line hidden
        
        
        #line 1399 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu ContextMenuTemplateLoad;
        
        #line default
        #line hidden
        
        
        #line 1408 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenButton;
        
        #line default
        #line hidden
        
        
        #line 1419 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveButton;
        
        #line default
        #line hidden
        
        
        #line 1430 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PrintButton;
        
        #line default
        #line hidden
        
        
        #line 1441 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ExportButton;
        
        #line default
        #line hidden
        
        
        #line 1455 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button UndoButton;
        
        #line default
        #line hidden
        
        
        #line 1466 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RedoButton;
        
        #line default
        #line hidden
        
        
        #line 1480 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton SelectToolButton;
        
        #line default
        #line hidden
        
        
        #line 1491 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton PanToolButton;
        
        #line default
        #line hidden
        
        
        #line 1501 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton DrawConnectorButton;
        
        #line default
        #line hidden
        
        
        #line 1514 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ConnectorButton;
        
        #line default
        #line hidden
        
        
        #line 1520 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Draw;
        
        #line default
        #line hidden
        
        
        #line 1530 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu ContextMenuConnector;
        
        #line default
        #line hidden
        
        
        #line 1531 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem PART_LineMenuItem;
        
        #line default
        #line hidden
        
        
        #line 1638 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Diagram.Stencil.Stencil stencil;
        
        #line default
        #line hidden
        
        
        #line 2032 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Diagram.SfDiagram Diagram;
        
        #line default
        #line hidden
        
        
        #line 2063 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PART_MinusZoomButton;
        
        #line default
        #line hidden
        
        
        #line 2072 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path minuspath;
        
        #line default
        #line hidden
        
        
        #line 2082 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider PART_ZoomSlider;
        
        #line default
        #line hidden
        
        
        #line 2093 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PART_PlusZoomButton;
        
        #line default
        #line hidden
        
        
        #line 2101 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pluspath;
        
        #line default
        #line hidden
        
        
        #line 2114 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PART_ButtonFitPage;
        
        #line default
        #line hidden
        
        
        #line 2121 "..\..\..\..\Views\NetworkDiagram.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path fitopagepath;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.networkdiagram.wpf;component/views/networkdiagram.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\NetworkDiagram.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SelectionTool = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 2:
            this.PanTool = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 3:
            this.DrawTool = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 4:
            this.ShowLines = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 5:
            this.SnapToGrid = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 6:
            this.SnapToObject = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 7:
            this.ShowRuler = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 8:
            this.ShowPageBreaks = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 9:
            this.FitToWidth = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 10:
            this.FitToPage = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 11:
            this.ResetView = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 12:
            this.NewButton = ((System.Windows.Controls.Button)(target));
            return;
            case 13:
            this.LoadFromTemplateButton = ((System.Windows.Controls.Button)(target));
            return;
            case 14:
            this.ContextMenuTemplateLoad = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 15:
            this.OpenButton = ((System.Windows.Controls.Button)(target));
            return;
            case 16:
            this.SaveButton = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.PrintButton = ((System.Windows.Controls.Button)(target));
            return;
            case 18:
            this.ExportButton = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.UndoButton = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.RedoButton = ((System.Windows.Controls.Button)(target));
            return;
            case 21:
            this.SelectToolButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 22:
            this.PanToolButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 23:
            this.DrawConnectorButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 24:
            this.ConnectorButton = ((System.Windows.Controls.Button)(target));
            return;
            case 25:
            this.Draw = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.ContextMenuConnector = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 27:
            this.PART_LineMenuItem = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 28:
            this.stencil = ((Syncfusion.UI.Xaml.Diagram.Stencil.Stencil)(target));
            return;
            case 29:
            this.Diagram = ((Syncfusion.UI.Xaml.Diagram.SfDiagram)(target));
            
            #line 2057 "..\..\..\..\Views\NetworkDiagram.xaml"
            this.Diagram.Loaded += new System.Windows.RoutedEventHandler(this.Diagram_Loaded);
            
            #line default
            #line hidden
            return;
            case 30:
            this.PART_MinusZoomButton = ((System.Windows.Controls.Button)(target));
            return;
            case 31:
            this.minuspath = ((System.Windows.Shapes.Path)(target));
            return;
            case 32:
            this.PART_ZoomSlider = ((System.Windows.Controls.Slider)(target));
            return;
            case 33:
            this.PART_PlusZoomButton = ((System.Windows.Controls.Button)(target));
            return;
            case 34:
            this.pluspath = ((System.Windows.Shapes.Path)(target));
            return;
            case 35:
            this.PART_ButtonFitPage = ((System.Windows.Controls.Button)(target));
            return;
            case 36:
            this.fitopagepath = ((System.Windows.Shapes.Path)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

