#pragma checksum "..\..\..\NotifyIcon\NotifyIconView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2642386E5F4EA38A5C729AEFC7ACB26AEB52A3B371C10587CE9710365C748CFE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xaml.Behaviors;
using Microsoft.Xaml.Behaviors.Core;
using Microsoft.Xaml.Behaviors.Input;
using Microsoft.Xaml.Behaviors.Layout;
using Microsoft.Xaml.Behaviors.Media;
using Syncfusion;
using Syncfusion.UI.Xaml.ProgressBar;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.notificationdemos.wpf;


namespace syncfusion.notificationdemos.wpf {
    
    
    /// <summary>
    /// NotifyIconDemo
    /// </summary>
    public partial class NotifyIconDemo : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "..\..\..\NotifyIcon\NotifyIconView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox balloonTipIcon;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\NotifyIcon\NotifyIconView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox balloonTipShape;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\NotifyIcon\NotifyIconView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox balloonTipAnimationEffect;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\NotifyIcon\NotifyIconView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox balloonTipHeaderVisibility;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\NotifyIcon\NotifyIconView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox balloonTipTitle;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\NotifyIcon\NotifyIconView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox balloonTipText;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\NotifyIcon\NotifyIconView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button button;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\..\NotifyIcon\NotifyIconView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.NotifyIcon notifyIcon;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.notificationdemos.wpf;component/notifyicon/notifyiconview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\NotifyIcon\NotifyIconView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.balloonTipIcon = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 2:
            this.balloonTipShape = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.balloonTipAnimationEffect = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.balloonTipHeaderVisibility = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.balloonTipTitle = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.balloonTipText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.button = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.notifyIcon = ((Syncfusion.Windows.Tools.Controls.NotifyIcon)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

