#pragma checksum "..\..\..\..\..\..\TabControlExt\View\MultiLine TabItem\MultiLineTabItem.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "613F2389BB0E4A03850CDFED042B27C35531FC69"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.UI.Xaml.Charts;
using Syncfusion.UI.Xaml.NavigationDrawer;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Layout;
using Syncfusion.Windows.Controls.Navigation;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.PropertyGrid;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.navigationdemos.wpf;


namespace syncfusion.navigationdemos.wpf {
    
    
    /// <summary>
    /// MultilineTabItemsDemosView
    /// </summary>
    public partial class MultilineTabItemsDemosView : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 52 "..\..\..\..\..\..\TabControlExt\View\MultiLine TabItem\MultiLineTabItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.TabControlExt tabControlExt;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\..\..\TabControlExt\View\MultiLine TabItem\MultiLineTabItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.TabControlExt tabControlExt1;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\..\..\TabControlExt\View\MultiLine TabItem\MultiLineTabItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.TabControlExt tabControlExt2;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\..\..\TabControlExt\View\MultiLine TabItem\MultiLineTabItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.TabControlExt tabControlExt3;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\..\..\..\..\TabControlExt\View\MultiLine TabItem\MultiLineTabItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Tools.Controls.TabControlExt tabControlExt4;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.navigationdemos.wpf;component/tabcontrolext/view/multiline%20tabitem/" +
                    "multilinetabitem.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\TabControlExt\View\MultiLine TabItem\MultiLineTabItem.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.tabControlExt = ((Syncfusion.Windows.Tools.Controls.TabControlExt)(target));
            return;
            case 2:
            this.tabControlExt1 = ((Syncfusion.Windows.Tools.Controls.TabControlExt)(target));
            return;
            case 3:
            this.tabControlExt2 = ((Syncfusion.Windows.Tools.Controls.TabControlExt)(target));
            return;
            case 4:
            this.tabControlExt3 = ((Syncfusion.Windows.Tools.Controls.TabControlExt)(target));
            return;
            case 5:
            this.tabControlExt4 = ((Syncfusion.Windows.Tools.Controls.TabControlExt)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

