#pragma checksum "..\..\..\..\Views\Customization.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "73AAC7A48A8AC807DBA40CD951D96D7CC0296C95"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.UI.Xaml.Gauges;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.gaugedemos.wpf;


namespace syncfusion.gaugedemos.wpf {
    
    
    /// <summary>
    /// Customization
    /// </summary>
    public partial class Customization : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.SfCircularGauge circularGauge1;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.CircularScale gauge1Scale;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.CircularRange gauge1Range;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.CircularPointer gauge1Pointer;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.SfCircularGauge circularGauge2;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.CircularScale gauge2Scale;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.CircularRange gauge2Range;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox rangePointerColor;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox needlePointerColor;
        
        #line default
        #line hidden
        
        
        #line 161 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox rangeColor;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\..\..\Views\Customization.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider slider;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.gaugedemos.wpf;component/views/customization.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\Customization.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.circularGauge1 = ((Syncfusion.UI.Xaml.Gauges.SfCircularGauge)(target));
            return;
            case 2:
            this.gauge1Scale = ((Syncfusion.UI.Xaml.Gauges.CircularScale)(target));
            return;
            case 3:
            this.gauge1Range = ((Syncfusion.UI.Xaml.Gauges.CircularRange)(target));
            return;
            case 4:
            this.gauge1Pointer = ((Syncfusion.UI.Xaml.Gauges.CircularPointer)(target));
            return;
            case 5:
            this.circularGauge2 = ((Syncfusion.UI.Xaml.Gauges.SfCircularGauge)(target));
            return;
            case 6:
            this.gauge2Scale = ((Syncfusion.UI.Xaml.Gauges.CircularScale)(target));
            return;
            case 7:
            this.gauge2Range = ((Syncfusion.UI.Xaml.Gauges.CircularRange)(target));
            return;
            case 8:
            this.rangePointerColor = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 9:
            this.needlePointerColor = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 10:
            this.rangeColor = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.slider = ((System.Windows.Controls.Slider)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

