#pragma checksum "..\..\..\..\Views\GettingStarted.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4F2F2F75C2487E2DCDC25FBD7A1A79FACD9BA517"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.UI.Xaml.Gauges;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;


namespace syncfusion.gaugedemos.wpf {
    
    
    /// <summary>
    /// GettingStarted
    /// </summary>
    public partial class GettingStarted : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "..\..\..\..\Views\GettingStarted.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.SfCircularGauge gauge1;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\Views\GettingStarted.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.CircularRange gauge1Range;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\Views\GettingStarted.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.SfCircularGauge gauge2;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\Views\GettingStarted.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Gauges.CircularScale gauge2Scale;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\..\..\Views\GettingStarted.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmb_RangePosition;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\..\..\Views\GettingStarted.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmb_LabelPosition;
        
        #line default
        #line hidden
        
        
        #line 224 "..\..\..\..\Views\GettingStarted.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmb_TickPosition;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.gaugedemos.wpf;component/views/gettingstarted.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\GettingStarted.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.gauge1 = ((Syncfusion.UI.Xaml.Gauges.SfCircularGauge)(target));
            return;
            case 2:
            this.gauge1Range = ((Syncfusion.UI.Xaml.Gauges.CircularRange)(target));
            return;
            case 3:
            this.gauge2 = ((Syncfusion.UI.Xaml.Gauges.SfCircularGauge)(target));
            return;
            case 4:
            this.gauge2Scale = ((Syncfusion.UI.Xaml.Gauges.CircularScale)(target));
            return;
            case 5:
            this.cmb_RangePosition = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.cmb_LabelPosition = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.cmb_TickPosition = ((System.Windows.Controls.ComboBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

