#pragma checksum "..\..\..\..\Views\XMLAndXAMLEditor.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "01ABAC97F4BF4CCDA89E3DF94BD07355EFE57C98"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Edit;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.syntaxeditordemos.wpf;


namespace syncfusion.syntaxeditordemos.wpf {
    
    
    /// <summary>
    /// XMLAndXAMLEditor
    /// </summary>
    public partial class XMLAndXAMLEditor : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.syntaxeditordemos.wpf.XMLAndXAMLEditor window;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Menu Mainmenu;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ToolBar Toolbar;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox fontlist;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox fontsize;
        
        #line default
        #line hidden
        
        
        #line 225 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl tabControl1;
        
        #line default
        #line hidden
        
        
        #line 231 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Edit.EditControl editXAML;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Edit.EditControl editXML;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.syntaxeditordemos.wpf;component/views/xmlandxamleditor.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\XMLAndXAMLEditor.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.window = ((syncfusion.syntaxeditordemos.wpf.XMLAndXAMLEditor)(target));
            return;
            case 2:
            this.Mainmenu = ((System.Windows.Controls.Menu)(target));
            return;
            case 3:
            this.Toolbar = ((System.Windows.Controls.ToolBar)(target));
            return;
            case 4:
            this.fontlist = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.fontsize = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.tabControl1 = ((System.Windows.Controls.TabControl)(target));
            return;
            case 7:
            this.editXAML = ((Syncfusion.Windows.Edit.EditControl)(target));
            return;
            case 8:
            this.editXML = ((Syncfusion.Windows.Edit.EditControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

