#pragma checksum "..\..\..\Views\FieldDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "6B98E1542B687C15BBB67D4AA4A9110BF7621BB0039512E8F5EABEE6A7C49D2E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.UI.Xaml.Charts;
using Syncfusion.UI.Xaml.Gauges;
using Syncfusion.UI.Xaml.Maps;
using Syncfusion.Windows;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace syncfusion.invoice.wpf {
    
    
    /// <summary>
    /// FieldDialog
    /// </summary>
    public partial class FieldDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 32 "..\..\..\Views\FieldDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTitle;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\Views\FieldDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox item;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Views\FieldDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Shared.UpDown quantity;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Views\FieldDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label rate;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\Views\FieldDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label taxesTextBlock;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\Views\FieldDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label totalAmount;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.invoice.wpf;component/views/fielddialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\FieldDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.lblTitle = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.item = ((System.Windows.Controls.ComboBox)(target));
            
            #line 45 "..\..\..\Views\FieldDialog.xaml"
            this.item.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.item_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.quantity = ((Syncfusion.Windows.Shared.UpDown)(target));
            
            #line 57 "..\..\..\Views\FieldDialog.xaml"
            this.quantity.ValueChanged += new System.Windows.PropertyChangedCallback(this.quantity_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.rate = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.taxesTextBlock = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.totalAmount = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            
            #line 100 "..\..\..\Views\FieldDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.updtButton_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 101 "..\..\..\Views\FieldDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.cancelButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

