#region Copyright Syncfusion Inc. 2001-2016.
// Copyright Syncfusion Inc. 2001-2016. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Syncfusion.Windows.Shared;
using System.Collections.ObjectModel;

namespace SkinManagerDemo_2008
{
    class GameCollect
    {
        #region Members
        /// <summary>
        /// Private Members 
        /// </summary>
        public static ObservableCollection<GameData> _GameCollection =
        new ObservableCollection<GameData>();

       

        /// <summary>
        /// Games the collections.
        /// </summary>
        public static void GameCollections()
        {
            _GameCollection.Add(new GameData
            {
                JobID = "101",
                CompanyName = "Photon InfoTech",
                CompanyID = "1001",
                JD = "Software Developer",
                Vacancy = "10",
                Date = "10.10.08 to 10.12.08",
                CN = "Photon Infotech",
                Intr = "Software Developer",
                JobID1 = "101a",
                CompanyName1 = "World Of Warcraft",
                CompanyID1 = "1001a",
                JD1 = "Hardware Technician",
                Vacancy1 = "5",
                Date1 = "09.25.08 to 09.26.08",
                CN1 = "World Of Warcraft",
                Intr1 = "HardWare Technician",
                JobID2 = "101b",
                CompanyName2 = "Polaris",
                CompanyID2 = "1001b",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.25.08 to 09.26.08",
                CN2 = "Q3 Technology",
                Intr2 = "Call Center",
                JobID3 = "101c",
                CompanyName3 = "Cosmosoft Solution",
                CompanyID3 = "1001c",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "09.27.08",
                CN3 = "Polaris",
                Intr3 = "BPO",
                JobID4 = "101d",
                CompanyName4 = "ACTE Group of Education",
                CompanyID4 = "1001d",
                JD4 = "Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ACTE Group of Education",
                Intr4 = "Lecturer",
                JobID5 = "101e",
                CompanyName5 = "ACTE Group of Education",
                CompanyID5 = "1001e",
                JD5 = "Cashier",
                Vacancy5 = "4",
                Date5 = "09.25.08 to 09.26.08",
                CN5 = "ACTE Group of Education",
                Intr5 = "Cashier"

            });
            _GameCollection.Add(new GameData
            {
                JobID = "102",
                CompanyName = "World Of Warcraft",
                CompanyID = "1002",
                JD = "Project Developer",
                Vacancy = "5",
                Date = "09.25.08 to 09.26.08",
                CN = "World Of Warcraft",
                Intr = "Software Developer",
                JobID1 = "102a",
                CompanyName1 = "Q3 Technology",
                CompanyID1 = "1002a",
                JD1 = "Hardware Trainee",
                Vacancy1 = "3",
                Date1 = "09.28.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Trainee",
                JobID2 = "102b",
                CompanyName2 = "World Of Warcraft",
                CompanyID2 = "1002b",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "2.10.08 to 5.10.08",
                CN2 = "World Of Warcraft",
                Intr2 = "Call Center",
                JobID3 = "102c",
                CompanyName3 = "SkyWare Technology",
                CompanyID3 = "1002c",
                JD3 = "BPO",
                Vacancy3 = "7",
                Date3 = "7.10.08 to 10.10.08",
                CN3 = "SkyWare Technology",
                Intr3 = "BPO",
                JobID4 = "102d",
                CompanyName4 = "CSC Computer",
                CompanyID4 = "1002d",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "1.10.08",
                CN4 = "CSC Computer",
                Intr4 = "Trainee",
                JobID5 = "102e",
                CompanyName5 = "ZepTo Tech",
                CompanyID5 = "1002e",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "2.10.08",
                CN5 = "ZeptoTech",
                Intr5 = "Senior Accountant"
            });
            _GameCollection.Add(new GameData
            {
                JobID = "103",
                CompanyName = "Polaris",
                CompanyID = "1003",
                JD = ".NET Developer",
                Vacancy = "15",
                Date = "09.25.08 to 09.26.08",
                CN = "Q3 Technology",
                Intr = "Team Leader",
                JobID1 = "103a",
                CompanyName1 = "Krupto Tech",
                CompanyID1 = "1003a",
                JD1 = "HardWare Technician",
                Vacancy1 = "2",
                Date1 = "2.10.08 to 5.10.08",
                CN1 = "Krupto Tech",
                Intr1 = "HardWare Technician",
                JobID2 = "103b",
                CompanyName2 = "Hexogan Technology",
                CompanyID2 = "1003b",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "5.10.08",
                CN2 = "Hexogan Technology",
                Intr2 = "Call Center",
                JobID3 = "103c",
                CompanyName3 = "World Of Warcraft",
                CompanyID3 = "1003c",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "2.10.08 to 5.10.08",
                CN3 = "World Of Warcraft",
                Intr3 = "BPO",
                JobID4 = "103d",
                CompanyName4 = "MIT Trainee Center",
                CompanyID4 = "1003d",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "2.10.08",
                CN4 = "MIT Trainee Center",
                Intr4 = "Trainee",

                JobID5 = "103e",
                CompanyName5 = "MIT Trainee Center",
                CompanyID5 = "1003e",
                JD5 = "Senior Accountant",
                Vacancy5 = "1",
                Date5 = "09.29.08",
                CN5 = "MIT Trainee Center",
                Intr5 = "Senior Accountant"
            });
            _GameCollection.Add(new GameData
            {
                JobID = "104",
                CompanyName = "Cosmosoft Solution",
                CompanyID = "1004",
                JD = "Project coordinator",
                Vacancy = "5",
                Date = "09.27.08",
                CN = "Polaris",
                Intr = ".NET Developer",
                JobID1 = "104a",
                CompanyID1 = "1004a",
                CompanyName1 = "Accenture",
                JD1 = "Technician",
                Vacancy1 = "5",
                Date1 = "09.27.08",
                CN1 = "Accenture",
                Intr1 = "Technician",
                JobID2 = "104b",
                CompanyID2 = "1004b",
                CompanyName2 = "IconTech",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.25.08 to 09.26.08",
                CN2 = "IconTech",
                Intr2 = "Call Center",
                JobID3 = "104c",
                CompanyID3 = "1004c",
                CompanyName3 = "Spam Tech",
                JD3 = "BPO",
                Vacancy3 = "10",
                Date3 = "1.10.08 to 2.10.08",
                CN3 = "Spam Tech",
                Intr3 = "BPO",
                JobID4 = "104d",
                CompanyID4 = "1004d",
                CompanyName4 = "APCOS College",
                JD4 = "Guest Lecturer",
                Vacancy4 = "2",
                Date4 = "09.25.08 to 09.26.08",
                CN4 = "APCOS College",
                Intr4 = "Guest Lecturer",
                JobID5 = "104e",
                CompanyID5 = "1004e",
                CompanyName5 = "APCOS College",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "09.28.08",
                CN5 = "APCOS College",
                Intr5 = "Accountant"
            });
            _GameCollection.Add(new GameData
            {
                JobID = "105",
                CompanyID = "1005",
                CompanyName = "Zeptoware Technology",
                JD = "Team leader",
                Vacancy = "2",
                Date = "09.27.08",
                CN = "Cosmosoft Solution",
                Intr = "Project Developer",
                JobID1 = "105a",
                CompanyID1 = "1005a",
                CompanyName1 = "World of WarCraft",
                JD1 = "Hardware Tester",
                Vacancy1 = "10",
                Date1 = "09.28.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Technician",
                JobID2 = "105b",
                CompanyID2 = "1005b",
                CompanyName2 = "TCS",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.25.08 to 09.26.08",
                CN2 = "TCS",
                Intr2 = "Call Center",
                JobID3 = "105c",
                CompanyID3 = "1005c",
                CompanyName3 = "CTS",
                JD3 = "BPO",
                Vacancy3 = "20",
                Date3 = "09.25.08 to 09.26.08",
                CN3 = "CTS",
                Intr3 = "BPO",
                JobID4 = "105d",
                CompanyID4 = "1005d",
                CompanyName4 = "ASMWC College",
                JD4 = "Senior Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ASMWC College",
                Intr4 = "Senior Lecturer",
                JobID5 = "105e",
                CompanyID5 = "1005e",
                CompanyName5 = "DenMark Pri. Ltd",
                JD5 = "Clerk",
                Vacancy5 = "2",
                Date5 = "09.26.08",
                CN5 = "DenMark Pri. Ltd",
                Intr5 = "Clerk"
            });
            _GameCollection.Add(new GameData
            {
                JobID = "101",
                CompanyID = "1001",
                CompanyName = "Photon InfoTech",
                JD = "Software Developer",
                Vacancy = "10",
                Date = "10.10.08 to 10.12.08",
                CN = "Photon Infotech",
                Intr = "Software Developer",
                JobID1 = "101a",
                CompanyID1 = "1001a",
                CompanyName1 = "World Of Warcraft",
                JD1 = "Hardware Technician",
                Vacancy1 = "5",
                Date1 = "09.25.08 to 09.26.08",
                CN1 = "World Of Warcraft",
                Intr1 = "HardWare Technician",
                JobID2 = "101b",
                CompanyName2 = "Polaris",
                CompanyID2 = "1001b",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.25.08 to 09.26.08",
                CN2 = "Q3 Technology",
                Intr2 = "Call Center",
                JobID3 = "101c",
                CompanyName3 = "Cosmosoft Solution",
                CompanyID3 = "1001c",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "09.27.08",
                CN3 = "Polaris",
                Intr3 = "BPO",
                JobID4 = "101d",
                CompanyID4 = "1001d",
                CompanyName4 = "ACTE Group of Education",
                JD4 = "Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ACTE Group of Education",
                Intr4 = "Lecturer",
                JobID5 = "101e",
                CompanyID5 = "1001e",
                CompanyName5 = "ACTE Group of Education",
                JD5 = "Cashier",
                Vacancy5 = "4",
                Date5 = "09.27.08 to 09.29.08",
                CN5 = "ACTE Group of Education",
                Intr5 = "Cashier"

            });
            _GameCollection.Add(new GameData
            {
                JobID = "102",
                CompanyID = "1002",
                CompanyName = "World Of Warcraft",
                JD = "Project Developer",
                Vacancy = "5",
                Date = "25.09.08 to 09.26.08",
                CN = "World Of Warcraft",
                Intr = "Software Developer",
                JobID1 = "102a",
                CompanyID1 = "1002a",
                CompanyName1 = "Q3 Technology",
                JD1 = "Hardware Trainee",
                Vacancy1 = "3",
                Date1 = "09.29.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Trainee",
                JobID2 = "102b",
                CompanyID2 = "1002b",
                CompanyName2 = "World Of Warcraft",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "2.10.08 to 5.10.08",
                CN2 = "World Of Warcraft",
                Intr2 = "Call Center",
                JobID3 = "102c",
                CompanyName3 = "SkyWare Technology",
                CompanyID3 = "1002c",
                JD3 = "BPO",
                Vacancy3 = "7",
                Date3 = "7.10.08 to 10.10.08",
                CN3 = "SkyWare Technology",
                Intr3 = "BPO",
                JobID4 = "102d",
                CompanyName4 = "CSC Computer",
                CompanyID4 = "1002d",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "1.10.08",
                CN4 = "CSC Computer",
                Intr4 = "Trainee",
                JobID5 = "102e",
                CompanyName5 = "ZepTo Tech",
                CompanyID5 = "1002e",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "2.10.08",
                CN5 = "ZeptoTech",
                Intr5 = "Senior Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1003a",
                CompanyID2 = "1003b",
                CompanyID3 = "1003c",
                CompanyID4 = "1003d",
                CompanyID5 = "1003e",
                CompanyID = "1003",
                JobID = "103",
                CompanyName = "Polaris",
                JD = ".NET Developer",
                Vacancy = "15",
                Date = "25.09.08 to 09.26.08",
                CN = "Q3 Technology",
                Intr = "Team Leader",
                JobID1 = "103a",
                CompanyName1 = "Krupto Tech",
                JD1 = "HardWare Technician",
                Vacancy1 = "2",
                Date1 = "2.10.08 to 5.10.08",
                CN1 = "Krupto Tech",
                Intr1 = "HardWare Technician",
                JobID2 = "103b",
                CompanyName2 = "Hexogan Technology",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "5.10.08",
                CN2 = "Hexogan Technology",
                Intr2 = "Call Center",
                JobID3 = "103c",
                CompanyName3 = "World Of Warcraft",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "2.10.08 to 5.10.08",
                CN3 = "World Of Warcraft",
                Intr3 = "BPO",
                JobID4 = "103d",
                CompanyName4 = "MIT Trainee Center",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "2.10.08",
                CN4 = "MIT Trainee Center",
                Intr4 = "Trainee",

                JobID5 = "103e",
                CompanyName5 = "MIT Trainee Center",
                JD5 = "Senior Accountant",
                Vacancy5 = "1",
                Date5 = "09.29.08",
                CN5 = "MIT Trainee Center",
                Intr5 = "Senior Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1004a",
                CompanyID2 = "1004b",
                CompanyID3 = "1004c",
                CompanyID4 = "1004d",
                CompanyID5 = "1004e",
                CompanyID = "1004",
                JobID = "104",
                CompanyName = "Cosmosoft Solution",
                JD = "Project coordinator",
                Vacancy = "5",
                Date = "09.27.08",
                CN = "Polaris",
                Intr = ".NET Developer",
                JobID1 = "104a",
                CompanyName1 = "Accenture",
                JD1 = "Technician",
                Vacancy1 = "5",
                Date1 = "09.27.08",
                CN1 = "Accenture",
                Intr1 = "Technician",
                JobID2 = "104b",
                CompanyName2 = "IconTech",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.29.08 to 09.30.08",
                CN2 = "IconTech",
                Intr2 = "Call Center",
                JobID3 = "104c",
                CompanyName3 = "Spam Tech",
                JD3 = "BPO",
                Vacancy3 = "10",
                Date3 = "1.10.08 to 2.10.08",
                CN3 = "Spam Tech",
                Intr3 = "BPO",
                JobID4 = "104d",
                CompanyName4 = "APCOS College",
                JD4 = "Guest Lecturer",
                Vacancy4 = "2",
                Date4 = "09.29.08 to 09.30.08",
                CN4 = "APCOS College",
                Intr4 = "Guest Lecturer",
                JobID5 = "104e",
                CompanyName5 = "APCOS College",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "09.28.08",
                CN5 = "APCOS College",
                Intr5 = "Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1005a",
                CompanyID2 = "1005b",
                CompanyID3 = "1005c",
                CompanyID4 = "1005d",
                CompanyID5 = "1005e",
                CompanyID = "1005",
                JobID = "105",
                CompanyName = "Zeptoware Technology",
                JD = "Team leader",
                Vacancy = "2",
                Date = "09.28.08",
                CN = "Cosmosoft Solution",
                Intr = "Project Developer",
                JobID1 = "105a",
                CompanyName1 = "World of WarCraft",
                JD1 = "Hardware Tester",
                Vacancy1 = "10",
                Date1 = "09.28.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Technician",
                JobID2 = "105b",
                CompanyName2 = "TCS",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.28.08 to 09.29.08",
                CN2 = "TCS",
                Intr2 = "Call Center",
                JobID3 = "105c",
                CompanyName3 = "CTS",
                JD3 = "BPO",
                Vacancy3 = "20",
                Date3 = "09.26.08 to 09.27.08",
                CN3 = "CTS",
                Intr3 = "BPO",
                JobID4 = "105d",
                CompanyName4 = "ASMWC College",
                JD4 = "Senior Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ASMWC College",
                Intr4 = "Senior Lecturer",
                JobID5 = "105e",
                CompanyName5 = "DenMark Pri. Ltd",
                JD5 = "Clerk",
                Vacancy5 = "2",
                Date5 = "09.26.08",
                CN5 = "DenMark Pri. Ltd",
                Intr5 = "Clerk"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1001a",
                CompanyID2 = "1001b",
                CompanyID3 = "1001c",
                CompanyID4 = "1001d",
                CompanyID5 = "1001e",
                CompanyID = "1001",
                JobID = "101",
                CompanyName = "Photon InfoTech",
                JD = "Software Developer",
                Vacancy = "10",
                Date = "10.10.08 to 12.10.08",
                CN = "Photon Infotech",
                Intr = "Software Developer",
                JobID1 = "101a",
                CompanyName1 = "World Of Warcraft",
                JD1 = "Hardware Technician",
                Vacancy1 = "5",
                Date1 = "25.09.08 to 09.26.08",
                CN1 = "World Of Warcraft",
                Intr1 = "HardWare Technician",
                JobID2 = "101b",
                CompanyName2 = "Polaris",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "25.09.08 to 09.26.08",
                CN2 = "Q3 Technology",
                Intr2 = "Call Center",
                JobID3 = "101c",
                CompanyName3 = "Cosmosoft Solution",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "09.27.08",
                CN3 = "Polaris",
                Intr3 = "BPO",
                JobID4 = "101d",
                CompanyName4 = "ACTE Group of Education",
                JD4 = "Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ACTE Group of Education",
                Intr4 = "Lecturer",
                JobID5 = "101e",
                CompanyName5 = "ACTE Group of Education",
                JD5 = "Cashier",
                Vacancy5 = "4",
                Date5 = "09.27.08 to 09.29.08",
                CN5 = "ACTE Group of Education",
                Intr5 = "Cashier"

            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1002a",
                CompanyID2 = "1002b",
                CompanyID3 = "1002c",
                CompanyID4 = "1002d",
                CompanyID5 = "1002e",
                CompanyID = "1002",
                JobID = "102",
                CompanyName = "World Of Warcraft",
                JD = "Project Developer",
                Vacancy = "5",
                Date = "09.25.08 to 26.09.08",
                CN = "World Of Warcraft",
                Intr = "Software Developer",
                JobID1 = "102a",
                CompanyName1 = "Q3 Technology",
                JD1 = "Hardware Trainee",
                Vacancy1 = "3",
                Date1 = "09.29.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Trainee",
                JobID2 = "102b",
                CompanyName2 = "World Of Warcraft",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "2.10.08 to 5.10.08",
                CN2 = "World Of Warcraft",
                Intr2 = "Call Center",
                JobID3 = "102c",
                CompanyName3 = "SkyWare Technology",
                JD3 = "BPO",
                Vacancy3 = "7",
                Date3 = "7.10.08 to 10.10.08",
                CN3 = "SkyWare Technology",
                Intr3 = "BPO",
                JobID4 = "102d",
                CompanyName4 = "CSC Computer",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "1.10.08",
                CN4 = "CSC Computer",
                Intr4 = "Trainee",
                JobID5 = "102e",
                CompanyName5 = "ZepTo Tech",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "2.10.08",
                CN5 = "ZeptoTech",
                Intr5 = "Senior Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1003a",
                CompanyID2 = "1003b",
                CompanyID3 = "1003c",
                CompanyID4 = "1003d",
                CompanyID5 = "1003e",
                CompanyID = "1003",
                JobID = "103",
                CompanyName = "Polaris",
                JD = ".NET Developer",
                Vacancy = "15",
                Date = "25.09.08 to 09.26.08",
                CN = "Q3 Technology",
                Intr = "Team Leader",
                JobID1 = "103a",
                CompanyName1 = "Krupto Tech",
                JD1 = "HardWare Technician",
                Vacancy1 = "2",
                Date1 = "2.10.08 to 5.10.08",
                CN1 = "Krupto Tech",
                Intr1 = "HardWare Technician",
                JobID2 = "103b",
                CompanyName2 = "Hexogan Technology",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "5.10.08",
                CN2 = "Hexogan Technology",
                Intr2 = "Call Center",
                JobID3 = "103c",
                CompanyName3 = "World Of Warcraft",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "2.10.08 to 5.10.08",
                CN3 = "World Of Warcraft",
                Intr3 = "BPO",
                JobID4 = "103d",
                CompanyName4 = "MIT Trainee Center",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "2.10.08",
                CN4 = "MIT Trainee Center",
                Intr4 = "Trainee",

                JobID5 = "103e",
                CompanyName5 = "MIT Trainee Center",
                JD5 = "Senior Accountant",
                Vacancy5 = "1",
                Date5 = "09.29.08",
                CN5 = "MIT Trainee Center",
                Intr5 = "Senior Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1004a",
                CompanyID2 = "1004b",
                CompanyID3 = "1004c",
                CompanyID4 = "1004d",
                CompanyID5 = "1004e",
                CompanyID = "1004",
                JobID = "104",
                CompanyName = "Cosmosoft Solution",
                JD = "Project coordinator",
                Vacancy = "5",
                Date = "09.27.08",
                CN = "Polaris",
                Intr = ".NET Developer",
                JobID1 = "104a",
                CompanyName1 = "Accenture",
                JD1 = "Technician",
                Vacancy1 = "5",
                Date1 = "09.27.08",
                CN1 = "Accenture",
                Intr1 = "Technician",
                JobID2 = "104b",
                CompanyName2 = "IconTech",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.29.08 to 09.30.08",
                CN2 = "IconTech",
                Intr2 = "Call Center",
                JobID3 = "104c",
                CompanyName3 = "Spam Tech",
                JD3 = "BPO",
                Vacancy3 = "10",
                Date3 = "1.10.08 to 2.10.08",
                CN3 = "Spam Tech",
                Intr3 = "BPO",
                JobID4 = "104d",
                CompanyName4 = "APCOS College",
                JD4 = "Guest Lecturer",
                Vacancy4 = "2",
                Date4 = "09.29.08 to 09.30.08",
                CN4 = "APCOS College",
                Intr4 = "Guest Lecturer",
                JobID5 = "104e",
                CompanyName5 = "APCOS College",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "09.28.08",
                CN5 = "APCOS College",
                Intr5 = "Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1005a",
                CompanyID2 = "1005b",
                CompanyID3 = "1005c",
                CompanyID4 = "1005d",
                CompanyID5 = "1005e",
                CompanyID = "1005",
                JobID = "105",
                CompanyName = "Zeptoware Technology",
                JD = "Team leader",
                Vacancy = "2",
                Date = "09.28.08",
                CN = "Cosmosoft Solution",
                Intr = "Project Developer",
                JobID1 = "105a",
                CompanyName1 = "World of WarCraft",
                JD1 = "Hardware Tester",
                Vacancy1 = "10",
                Date1 = "09.28.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Technician",
                JobID2 = "105b",
                CompanyName2 = "TCS",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.28.08 to 09.29.08",
                CN2 = "TCS",
                Intr2 = "Call Center",
                JobID3 = "105c",
                CompanyName3 = "CTS",
                JD3 = "BPO",
                Vacancy3 = "20",
                Date3 = "09.26.08 to 09.27.08",
                CN3 = "CTS",
                Intr3 = "BPO",
                JobID4 = "105d",
                CompanyName4 = "ASMWC College",
                JD4 = "Senior Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ASMWC College",
                Intr4 = "Senior Lecturer",
                JobID5 = "105e",
                CompanyName5 = "DenMark Pri. Ltd",
                JD5 = "Clerk",
                Vacancy5 = "2",
                Date5 = "09.26.08",
                CN5 = "DenMark Pri. Ltd",
                Intr5 = "Clerk"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1001a",
                CompanyID2 = "1001b",
                CompanyID3 = "1001c",
                CompanyID4 = "1001d",
                CompanyID5 = "1001e",
                CompanyID = "1001",
                JobID = "101",
                CompanyName = "Photon InfoTech",
                JD = "Software Developer",
                Vacancy = "10",
                Date = "10.10.08 to 12.10.08",
                CN = "Photon Infotech",
                Intr = "Software Developer",
                JobID1 = "101a",
                CompanyName1 = "World Of Warcraft",
                JD1 = "Hardware Technician",
                Vacancy1 = "5",
                Date1 = "25.09.08 to 09.26.08",
                CN1 = "World Of Warcraft",
                Intr1 = "HardWare Technician",
                JobID2 = "101b",
                CompanyName2 = "Polaris",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "25.09.08 to 09.26.08",
                CN2 = "Q3 Technology",
                Intr2 = "Call Center",
                JobID3 = "101c",
                CompanyName3 = "Cosmosoft Solution",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "09.27.08",
                CN3 = "Polaris",
                Intr3 = "BPO",
                JobID4 = "101d",
                CompanyName4 = "ACTE Group of Education",
                JD4 = "Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ACTE Group of Education",
                Intr4 = "Lecturer",
                JobID5 = "101e",
                CompanyName5 = "ACTE Group of Education",
                JD5 = "Cashier",
                Vacancy5 = "4",
                Date5 = "09.27.08 to 09.29.08",
                CN5 = "ACTE Group of Education",
                Intr5 = "Cashier"

            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1002a",
                CompanyID2 = "1002b",
                CompanyID3 = "1002c",
                CompanyID4 = "1002d",
                CompanyID5 = "1002e",
                CompanyID = "1002",
                JobID = "102",
                CompanyName = "World Of Warcraft",
                JD = "Project Developer",
                Vacancy = "5",
                Date = "25.09.08 to 09.26.08",
                CN = "World Of Warcraft",
                Intr = "Software Developer",
                JobID1 = "102a",
                CompanyName1 = "Q3 Technology",
                JD1 = "Hardware Trainee",
                Vacancy1 = "3",
                Date1 = "09.29.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Trainee",
                JobID2 = "102b",
                CompanyName2 = "World Of Warcraft",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "2.10.08 to 5.10.08",
                CN2 = "World Of Warcraft",
                Intr2 = "Call Center",
                JobID3 = "102c",
                CompanyName3 = "SkyWare Technology",
                JD3 = "BPO",
                Vacancy3 = "7",
                Date3 = "7.10.08 to 10.10.08",
                CN3 = "SkyWare Technology",
                Intr3 = "BPO",
                JobID4 = "102d",
                CompanyName4 = "CSC Computer",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "1.10.08",
                CN4 = "CSC Computer",
                Intr4 = "Trainee",
                JobID5 = "102e",
                CompanyName5 = "ZepTo Tech",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "2.10.08",
                CN5 = "ZeptoTech",
                Intr5 = "Senior Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1003a",
                CompanyID2 = "1003b",
                CompanyID3 = "1003c",
                CompanyID4 = "1003d",
                CompanyID5 = "1003e",
                CompanyID = "1003",
                JobID = "103",
                CompanyName = "Polaris",
                JD = ".NET Developer",
                Vacancy = "15",
                Date = "25.09.08 to 09.26.08",
                CN = "Q3 Technology",
                Intr = "Team Leader",
                JobID1 = "103a",
                CompanyName1 = "Krupto Tech",
                JD1 = "HardWare Technician",
                Vacancy1 = "2",
                Date1 = "2.10.08 to 5.10.08",
                CN1 = "Krupto Tech",
                Intr1 = "HardWare Technician",
                JobID2 = "103b",
                CompanyName2 = "Hexogan Technology",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "5.10.08",
                CN2 = "Hexogan Technology",
                Intr2 = "Call Center",
                JobID3 = "103c",
                CompanyName3 = "World Of Warcraft",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "2.10.08 to 5.10.08",
                CN3 = "World Of Warcraft",
                Intr3 = "BPO",
                JobID4 = "103d",
                CompanyName4 = "MIT Trainee Center",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "2.10.08",
                CN4 = "MIT Trainee Center",
                Intr4 = "Trainee",

                JobID5 = "103e",
                CompanyName5 = "MIT Trainee Center",
                JD5 = "Senior Accountant",
                Vacancy5 = "1",
                Date5 = "09.29.08",
                CN5 = "MIT Trainee Center",
                Intr5 = "Senior Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1004a",
                CompanyID2 = "1004b",
                CompanyID3 = "1004c",
                CompanyID4 = "1004d",
                CompanyID5 = "1004e",
                CompanyID = "1004",
                JobID = "104",
                CompanyName = "Cosmosoft Solution",
                JD = "Project coordinator",
                Vacancy = "5",
                Date = "09.27.08",
                CN = "Polaris",
                Intr = ".NET Developer",
                JobID1 = "104a",
                CompanyName1 = "Accenture",
                JD1 = "Technician",
                Vacancy1 = "5",
                Date1 = "09.27.08",
                CN1 = "Accenture",
                Intr1 = "Technician",
                JobID2 = "104b",
                CompanyName2 = "IconTech",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.29.08 to 09.30.08",
                CN2 = "IconTech",
                Intr2 = "Call Center",
                JobID3 = "104c",
                CompanyName3 = "Spam Tech",
                JD3 = "BPO",
                Vacancy3 = "10",
                Date3 = "1.10.08 to 2.10.08",
                CN3 = "Spam Tech",
                Intr3 = "BPO",
                JobID4 = "104d",
                CompanyName4 = "APCOS College",
                JD4 = "Guest Lecturer",
                Vacancy4 = "2",
                Date4 = "09.29.08 to 09.30.08",
                CN4 = "APCOS College",
                Intr4 = "Guest Lecturer",
                JobID5 = "104e",
                CompanyName5 = "APCOS College",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "09.28.08",
                CN5 = "APCOS College",
                Intr5 = "Accountant"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1005a",
                CompanyID2 = "1005b",
                CompanyID3 = "1005c",
                CompanyID4 = "1005d",
                CompanyID5 = "1005e",
                CompanyID = "1005",
                JobID = "105",
                CompanyName = "Zeptoware Technology",
                JD = "Team leader",
                Vacancy = "2",
                Date = "09.28.08",
                CN = "Cosmosoft Solution",
                Intr = "Project Developer",
                JobID1 = "105a",
                CompanyName1 = "World of WarCraft",
                JD1 = "Hardware Tester",
                Vacancy1 = "10",
                Date1 = "09.28.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Technician",
                JobID2 = "105b",
                CompanyName2 = "TCS",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "09.28.08 to 09.29.08",
                CN2 = "TCS",
                Intr2 = "Call Center",
                JobID3 = "105c",
                CompanyName3 = "CTS",
                JD3 = "BPO",
                Vacancy3 = "20",
                Date3 = "09.26.08 to 09.27.08",
                CN3 = "CTS",
                Intr3 = "BPO",
                JobID4 = "105d",
                CompanyName4 = "ASMWC College",
                JD4 = "Senior Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ASMWC College",
                Intr4 = "Senior Lecturer",
                JobID5 = "105e",
                CompanyName5 = "DenMark Pri. Ltd",
                JD5 = "Clerk",
                Vacancy5 = "2",
                Date5 = "09.26.08",
                CN5 = "DenMark Pri. Ltd",
                Intr5 = "Clerk"
            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1001a",
                CompanyID2 = "1001b",
                CompanyID3 = "1001c",
                CompanyID4 = "1001d",
                CompanyID5 = "1001e",
                CompanyID = "1001",
                JobID = "101",
                CompanyName = "Photon InfoTech",
                JD = "Software Developer",
                Vacancy = "10",
                Date = "10.10.08 to 12.10.08",
                CN = "Photon Infotech",
                Intr = "Software Developer",
                JobID1 = "101a",
                CompanyName1 = "World Of Warcraft",
                JD1 = "Hardware Technician",
                Vacancy1 = "5",
                Date1 = "25.09.08 to 09.26.08",
                CN1 = "World Of Warcraft",
                Intr1 = "HardWare Technician",
                JobID2 = "101b",
                CompanyName2 = "Polaris",
                JD2 = "Call Center",
                Vacancy2 = "15",
                Date2 = "25.09.08 to 09.26.08",
                CN2 = "Q3 Technology",
                Intr2 = "Call Center",
                JobID3 = "101c",
                CompanyName3 = "Cosmosoft Solution",
                JD3 = "BPO",
                Vacancy3 = "5",
                Date3 = "09.27.08",
                CN3 = "Polaris",
                Intr3 = "BPO",
                JobID4 = "101d",
                CompanyName4 = "ACTE Group of Education",
                JD4 = "Lecturer",
                Vacancy4 = "2",
                Date4 = "09.28.08",
                CN4 = "ACTE Group of Education",
                Intr4 = "Lecturer",
                JobID5 = "101e",
                CompanyName5 = "ACTE Group of Education",
                JD5 = "Cashier",
                Vacancy5 = "4",
                Date5 = "09.27.08 to 09.29.08",
                CN5 = "ACTE Group of Education",
                Intr5 = "Cashier"

            });
            _GameCollection.Add(new GameData
            {
                CompanyID1 = "1002a",
                CompanyID2 = "1002b",
                CompanyID3 = "1002c",
                CompanyID4 = "1002d",
                CompanyID5 = "1002e",
                CompanyID = "1002",
                JobID = "102",
                CompanyName = "World Of Warcraft",
                JD = "Project Developer",
                Vacancy = "5",
                Date = "25.09.08 to 09.26.08",
                CN = "World Of Warcraft",
                Intr = "Software Developer",
                JobID1 = "102a",
                CompanyName1 = "Q3 Technology",
                JD1 = "Hardware Trainee",
                Vacancy1 = "3",
                Date1 = "09.29.08",
                CN1 = "Q3 Technology",
                Intr1 = "Hardware Trainee",
                JobID2 = "102b",
                CompanyName2 = "World Of Warcraft",
                JD2 = "Call Center",
                Vacancy2 = "5",
                Date2 = "2.10.08 to 5.10.08",
                CN2 = "World Of Warcraft",
                Intr2 = "Call Center",
                JobID3 = "102c",
                CompanyName3 = "SkyWare Technology",
                JD3 = "BPO",
                Vacancy3 = "7",
                Date3 = "7.10.08 to 10.10.08",
                CN3 = "SkyWare Technology",
                Intr3 = "BPO",
                JobID4 = "102d",
                CompanyName4 = "CSC Computer",
                JD4 = "Trainee",
                Vacancy4 = "2",
                Date4 = "1.10.08",
                CN4 = "CSC Computer",
                Intr4 = "Trainee",
                JobID5 = "102e",
                CompanyName5 = "ZepTo Tech",
                JD5 = "Accountant",
                Vacancy5 = "1",
                Date5 = "2.10.08",
                CN5 = "ZeptoTech",
                Intr5 = "Senior Accountant"
            });
        }

        #endregion
    }
}
