#pragma checksum "..\..\..\..\Views\Filters.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E1CCEB70DE672B3EF08BF98B04114C815583DE94"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;


namespace syncfusion.xlsiodemos.wpf {
    
    
    /// <summary>
    /// Filters
    /// </summary>
    public partial class Filters : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DataManagement;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock1;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock2;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock3;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock4;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock5;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox3;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label4;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbAlgorithm;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button button2;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button button3;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox advanced;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox fAction;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdb1;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdb2;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox colorFilter;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox fType;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdb3;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdb4;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label color;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comboBox;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox iconFilter;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label iconSet;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox iconSetType;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label icon;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\..\..\Views\Filters.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox iconIdComboBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.xlsiodemos.wpf;component/views/filters.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\Filters.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DataManagement = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.textBlock1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.textBlock2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.textBlock3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.textBlock4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.textBlock5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.groupBox3 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 8:
            this.label4 = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.cmbAlgorithm = ((System.Windows.Controls.ComboBox)(target));
            
            #line 55 "..\..\..\..\Views\Filters.xaml"
            this.cmbAlgorithm.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cmbAlgorithm_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.button2 = ((System.Windows.Controls.Button)(target));
            
            #line 56 "..\..\..\..\Views\Filters.xaml"
            this.button2.Click += new System.Windows.RoutedEventHandler(this.button2_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.button3 = ((System.Windows.Controls.Button)(target));
            
            #line 57 "..\..\..\..\Views\Filters.xaml"
            this.button3.Click += new System.Windows.RoutedEventHandler(this.button3_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.advanced = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 13:
            this.fAction = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 14:
            this.rdb1 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 15:
            this.rdb2 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 16:
            this.checkBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 17:
            this.colorFilter = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 18:
            this.fType = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 19:
            this.rdb3 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 20:
            this.rdb4 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 21:
            this.color = ((System.Windows.Controls.Label)(target));
            return;
            case 22:
            this.comboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 23:
            this.iconFilter = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 24:
            this.iconSet = ((System.Windows.Controls.Label)(target));
            return;
            case 25:
            this.iconSetType = ((System.Windows.Controls.ComboBox)(target));
            
            #line 98 "..\..\..\..\Views\Filters.xaml"
            this.iconSetType.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.IconSetChanged);
            
            #line default
            #line hidden
            return;
            case 26:
            this.icon = ((System.Windows.Controls.Label)(target));
            return;
            case 27:
            this.iconIdComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

