#pragma checksum "..\..\..\..\Views\ImportExportDataTable.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A4C8A185F087B19A23600D6A0099F6DF51FFCB1E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.UI.Xaml.Charts;
using Syncfusion.UI.Xaml.Controls.DataPager;
using Syncfusion.UI.Xaml.Grid;
using Syncfusion.UI.Xaml.Grid.RowFilter;
using Syncfusion.UI.Xaml.TreeGrid;
using Syncfusion.UI.Xaml.TreeGrid.Filtering;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;


namespace syncfusion.xlsiodemos.wpf {
    
    
    /// <summary>
    /// ImportExportDataTable
    /// </summary>
    public partial class ImportExportDataTable : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 14 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DataBinding;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock1;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock2;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock3;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock4;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock5;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock6;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock7;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock8;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock9;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer gridScroller;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Root_Grid;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Grid.SfDataGrid dataGrid;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock10;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnSkip;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnReplace;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnStop;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnXls;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnXlsx;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnInput;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnImport;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\Views\ImportExportDataTable.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnExport;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.xlsiodemos.wpf;component/views/importexportdatatable.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\ImportExportDataTable.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DataBinding = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.textBlock1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.textBlock2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.textBlock3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.textBlock4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.textBlock5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.textBlock6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.textBlock7 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.textBlock8 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.textBlock9 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.gridScroller = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 12:
            this.Root_Grid = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            this.dataGrid = ((Syncfusion.UI.Xaml.Grid.SfDataGrid)(target));
            return;
            case 14:
            this.textBlock10 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.rdbtnSkip = ((System.Windows.Controls.RadioButton)(target));
            
            #line 70 "..\..\..\..\Views\ImportExportDataTable.xaml"
            this.rdbtnSkip.Click += new System.Windows.RoutedEventHandler(this.btnExport_Disable);
            
            #line default
            #line hidden
            return;
            case 16:
            this.rdbtnReplace = ((System.Windows.Controls.RadioButton)(target));
            
            #line 71 "..\..\..\..\Views\ImportExportDataTable.xaml"
            this.rdbtnReplace.Click += new System.Windows.RoutedEventHandler(this.btnExport_Disable);
            
            #line default
            #line hidden
            return;
            case 17:
            this.rdbtnStop = ((System.Windows.Controls.RadioButton)(target));
            
            #line 72 "..\..\..\..\Views\ImportExportDataTable.xaml"
            this.rdbtnStop.Click += new System.Windows.RoutedEventHandler(this.btnExport_Disable);
            
            #line default
            #line hidden
            return;
            case 18:
            this.rdbtnXls = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 19:
            this.rdbtnXlsx = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 20:
            this.btnInput = ((System.Windows.Controls.Button)(target));
            
            #line 88 "..\..\..\..\Views\ImportExportDataTable.xaml"
            this.btnInput.Click += new System.Windows.RoutedEventHandler(this.btnInput_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.btnImport = ((System.Windows.Controls.Button)(target));
            
            #line 89 "..\..\..\..\Views\ImportExportDataTable.xaml"
            this.btnImport.Click += new System.Windows.RoutedEventHandler(this.btnImport_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.btnExport = ((System.Windows.Controls.Button)(target));
            
            #line 90 "..\..\..\..\Views\ImportExportDataTable.xaml"
            this.btnExport.Click += new System.Windows.RoutedEventHandler(this.btnExport_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

