#pragma checksum "..\..\..\..\PulsingTile\PulsingTileView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3D5F48DEA32FAC118C5FC1B2BE32FDDFC6A2AF89"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.UI.Xaml.ProgressBar;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.notificationdemos.wpf;


namespace syncfusion.notificationdemos.wpf {
    
    
    /// <summary>
    /// PulsingTileView
    /// </summary>
    public partial class PulsingTileView : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.notificationdemos.wpf.PulsingTileView window;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock headerTextBlock;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Input.SfTextBoxExt header;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock pulseDurationTextBlock;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Shared.TimeSpanEdit timeSpanEdit;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock pulseScaleTextBlock;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Shared.UpDown pulsingScaleUpDown;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Notification.SfPulsingTile pulsingTile;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.notificationdemos.wpf;component/pulsingtile/pulsingtileview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\PulsingTile\PulsingTileView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.window = ((syncfusion.notificationdemos.wpf.PulsingTileView)(target));
            return;
            case 2:
            this.headerTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.header = ((Syncfusion.Windows.Controls.Input.SfTextBoxExt)(target));
            return;
            case 4:
            this.pulseDurationTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.timeSpanEdit = ((Syncfusion.Windows.Shared.TimeSpanEdit)(target));
            return;
            case 6:
            this.pulseScaleTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.pulsingScaleUpDown = ((Syncfusion.Windows.Shared.UpDown)(target));
            return;
            case 8:
            this.pulsingTile = ((Syncfusion.Windows.Controls.Notification.SfPulsingTile)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

