#region Copyright Syncfusion Inc. 2001-2019.
// Copyright Syncfusion Inc. 2001-2019. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syncfusion_SfGrid_WPF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syncfusion_SfGrid_WPF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationDemo.Resources.Syncfusion.SfGrid.WPF", typeof(Syncfusion_SfGrid_WPF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add a new row.
        /// </summary>
        internal static string AddNewRowText {
            get {
                return ResourceManager.GetString("AddNewRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Filters.
        /// </summary>
        internal static string AdvancedFiltersButtonText {
            get {
                return ResourceManager.GetString("AdvancedFiltersButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Or Equal.
        /// </summary>
        internal static string AfterOrEqual {
            get {
                return ResourceManager.GetString("AfterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Or Equal.
        /// </summary>
        internal static string BeforeOrEqual {
            get {
                return ResourceManager.GetString("BeforeOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins With.
        /// </summary>
        internal static string BeginsWith {
            get {
                return ResourceManager.GetString("BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blanks).
        /// </summary>
        internal static string Blanks {
            get {
                return ResourceManager.GetString("Blanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string ColumnChooserTitle {
            get {
                return ResourceManager.GetString("ColumnChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Fields Available).
        /// </summary>
        internal static string ColumnChooserWaterMark {
            get {
                return ResourceManager.GetString("ColumnChooserWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Margin.
        /// </summary>
        internal static string CustomMargin {
            get {
                return ResourceManager.GetString("CustomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Margins.
        /// </summary>
        internal static string CustomMargins {
            get {
                return ResourceManager.GetString("CustomMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Page Sizes.
        /// </summary>
        internal static string CustomPageSizes {
            get {
                return ResourceManager.GetString("CustomPageSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Size.
        /// </summary>
        internal static string CustomSize {
            get {
                return ResourceManager.GetString("CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Filters.
        /// </summary>
        internal static string DateFilters {
            get {
                return ResourceManager.GetString("DateFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Filter Value.
        /// </summary>
        internal static string EnterValidFilterValue {
            get {
                return ResourceManager.GetString("EnterValidFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string Equalss {
            get {
                return ResourceManager.GetString("Equalss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit All Columns on One Page.
        /// </summary>
        internal static string FitAllColumnsonOnePage {
            get {
                return ResourceManager.GetString("FitAllColumnsonOnePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit All Rows on One Page.
        /// </summary>
        internal static string FitAllRowsOnOnePage {
            get {
                return ResourceManager.GetString("FitAllRowsOnOnePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Grid on One Page.
        /// </summary>
        internal static string FitGridOnOnePage {
            get {
                return ResourceManager.GetString("FitGridOnOnePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than or Equal.
        /// </summary>
        internal static string GreaterThanorEqual {
            get {
                return ResourceManager.GetString("GreaterThanorEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        internal static string GroupDropAreaText {
            get {
                return ResourceManager.GetString("GroupDropAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandScape Orientation.
        /// </summary>
        internal static string LandScapeOrientation {
            get {
                return ResourceManager.GetString("LandScapeOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than or Equal.
        /// </summary>
        internal static string LessThanorEqual {
            get {
                return ResourceManager.GetString("LessThanorEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case .
        /// </summary>
        internal static string MatchCaseToolTip {
            get {
                return ResourceManager.GetString("MatchCaseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        internal static string Moderate {
            get {
                return ResourceManager.GetString("Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow.
        /// </summary>
        internal static string Narrow {
            get {
                return ResourceManager.GetString("Narrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matches.
        /// </summary>
        internal static string NoMatches {
            get {
                return ResourceManager.GetString("NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scaling.
        /// </summary>
        internal static string NoScaling {
            get {
                return ResourceManager.GetString("NoScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Contain.
        /// </summary>
        internal static string NotContains {
            get {
                return ResourceManager.GetString("NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Empty.
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Equal.
        /// </summary>
        internal static string NotEquals {
            get {
                return ResourceManager.GetString("NotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Null.
        /// </summary>
        internal static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Filters.
        /// </summary>
        internal static string NumberFilters {
            get {
                return ResourceManager.GetString("NumberFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait Orientation.
        /// </summary>
        internal static string PortraitOrientation {
            get {
                return ResourceManager.GetString("PortraitOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        internal static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Print.
        /// </summary>
        internal static string QuickPrint {
            get {
                return ResourceManager.GetString("QuickPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Containing Error.
        /// </summary>
        internal static string RowErrorMessage {
            get {
                return ResourceManager.GetString("RowErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select All).
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        internal static string SelectDateToolTip {
            get {
                return ResourceManager.GetString("SelectDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rows where:.
        /// </summary>
        internal static string ShowRowsWhere {
            get {
                return ResourceManager.GetString("ShowRowsWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Oldest to Newest.
        /// </summary>
        internal static string SortDateAscending {
            get {
                return ResourceManager.GetString("SortDateAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Newest to Oldest.
        /// </summary>
        internal static string SortDateDescending {
            get {
                return ResourceManager.GetString("SortDateDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Smallest to Largest.
        /// </summary>
        internal static string SortNumberAscending {
            get {
                return ResourceManager.GetString("SortNumberAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Largest to Smallest.
        /// </summary>
        internal static string SortNumberDescending {
            get {
                return ResourceManager.GetString("SortNumberDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort A to Z.
        /// </summary>
        internal static string SortStringAscending {
            get {
                return ResourceManager.GetString("SortStringAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Z to A.
        /// </summary>
        internal static string SortStringDescending {
            get {
                return ResourceManager.GetString("SortStringDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Filters.
        /// </summary>
        internal static string TextFilters {
            get {
                return ResourceManager.GetString("TextFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide.
        /// </summary>
        internal static string Wide {
            get {
                return ResourceManager.GetString("Wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
