#pragma checksum "..\..\..\..\..\Views\Appearance\ToolTip.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "18B2C5AB9B8E99B134DE2367D6305942366C5E6A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.PivotAnalysis.Base;
using Syncfusion.SfSkinManager;
using Syncfusion.UI.Xaml.Controls.DataPager;
using Syncfusion.UI.Xaml.Grid;
using Syncfusion.UI.Xaml.Grid.RowFilter;
using Syncfusion.UI.Xaml.TreeGrid;
using Syncfusion.UI.Xaml.TreeGrid.Filtering;
using Syncfusion.Windows;
using Syncfusion.Windows.Collections;
using Syncfusion.Windows.ComponentModel;
using Syncfusion.Windows.Controls.Cells;
using Syncfusion.Windows.Controls.Grid;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Controls.PivotGrid;
using Syncfusion.Windows.Controls.PivotSchemaDesigner;
using Syncfusion.Windows.Controls.Scroll;
using Syncfusion.Windows.Controls.VirtualTreeView;
using Syncfusion.Windows.Data;
using Syncfusion.Windows.Diagnostics;
using Syncfusion.Windows.GridCommon;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Styles;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.pivotgriddemos.wpf;


namespace syncfusion.pivotgriddemos.wpf {
    
    
    /// <summary>
    /// ToolTip
    /// </summary>
    public partial class ToolTip : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 112 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.PivotGrid.PivotGridControl pivotGrid1;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.PivotSchemaDesigner.PivotSchemaDesigner SchemaDesigner;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxToolTipEnabled;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox tooltipGroupBox;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxColHeader;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxRowHeader;
        
        #line default
        #line hidden
        
        
        #line 223 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxValCell;
        
        #line default
        #line hidden
        
        
        #line 230 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxSumHeader;
        
        #line default
        #line hidden
        
        
        #line 237 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxSumCell;
        
        #line default
        #line hidden
        
        
        #line 245 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox customTooltipGroupBox;
        
        #line default
        #line hidden
        
        
        #line 259 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxEnableCustom_All;
        
        #line default
        #line hidden
        
        
        #line 265 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxCustomColHeader;
        
        #line default
        #line hidden
        
        
        #line 271 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxCustomRowHeader;
        
        #line default
        #line hidden
        
        
        #line 277 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxCustomValCell;
        
        #line default
        #line hidden
        
        
        #line 283 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxCustomSumHeader;
        
        #line default
        #line hidden
        
        
        #line 289 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkBoxCustomSumCell;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.pivotgriddemos.wpf;component/views/appearance/tooltip.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pivotGrid1 = ((Syncfusion.Windows.Controls.PivotGrid.PivotGridControl)(target));
            return;
            case 2:
            this.SchemaDesigner = ((Syncfusion.Windows.Controls.PivotSchemaDesigner.PivotSchemaDesigner)(target));
            return;
            case 3:
            this.chkBoxToolTipEnabled = ((System.Windows.Controls.CheckBox)(target));
            
            #line 190 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxToolTipEnabled.Click += new System.Windows.RoutedEventHandler(this.chkBoxToolTipEnabled_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.tooltipGroupBox = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 5:
            this.chkBoxColHeader = ((System.Windows.Controls.CheckBox)(target));
            
            #line 212 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxColHeader.Click += new System.Windows.RoutedEventHandler(this.chkBoxColHeader_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.chkBoxRowHeader = ((System.Windows.Controls.CheckBox)(target));
            
            #line 219 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxRowHeader.Click += new System.Windows.RoutedEventHandler(this.chkBoxRowHeader_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.chkBoxValCell = ((System.Windows.Controls.CheckBox)(target));
            
            #line 226 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxValCell.Click += new System.Windows.RoutedEventHandler(this.chkBoxValCell_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.chkBoxSumHeader = ((System.Windows.Controls.CheckBox)(target));
            
            #line 233 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxSumHeader.Click += new System.Windows.RoutedEventHandler(this.chkBoxSumHeader_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.chkBoxSumCell = ((System.Windows.Controls.CheckBox)(target));
            
            #line 240 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxSumCell.Click += new System.Windows.RoutedEventHandler(this.chkBoxSumCell_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.customTooltipGroupBox = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 11:
            this.chkBoxEnableCustom_All = ((System.Windows.Controls.CheckBox)(target));
            
            #line 261 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxEnableCustom_All.Click += new System.Windows.RoutedEventHandler(this.chkBoxEnableCustom_All_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.chkBoxCustomColHeader = ((System.Windows.Controls.CheckBox)(target));
            
            #line 268 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxCustomColHeader.Click += new System.Windows.RoutedEventHandler(this.chkBoxCustomColHeader_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.chkBoxCustomRowHeader = ((System.Windows.Controls.CheckBox)(target));
            
            #line 274 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxCustomRowHeader.Click += new System.Windows.RoutedEventHandler(this.chkBoxCustomRowHeader_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.chkBoxCustomValCell = ((System.Windows.Controls.CheckBox)(target));
            
            #line 280 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxCustomValCell.Click += new System.Windows.RoutedEventHandler(this.chkBoxCustomValCell_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.chkBoxCustomSumHeader = ((System.Windows.Controls.CheckBox)(target));
            
            #line 286 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxCustomSumHeader.Click += new System.Windows.RoutedEventHandler(this.chkBoxCustomSumHeader_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.chkBoxCustomSumCell = ((System.Windows.Controls.CheckBox)(target));
            
            #line 292 "..\..\..\..\..\Views\Appearance\ToolTip.xaml"
            this.chkBoxCustomSumCell.Click += new System.Windows.RoutedEventHandler(this.chkBoxCustomSumCell_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

